echo "Starting setup_cli.sh"

echo "Installing Zsh"
apt install -y zsh
echo "Zsh install Done"

echo "Changing default shell to 'zsh'"
chsh -s $(which zsh)
echo "Default shell to zsh done"

echo "Installing Oh My Zsh, instructions via https://ohmyz.sh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
echo "Oh my Zsh Done"

echo "Installing Claude Code, instructions via https://code.claude.com/docs/en/quickstart"
curl -fsSL https://claude.ai/install.sh | bash

# Add `claude` to path
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
echo "Claude Code Done"

# Check for Git setup (generated by claude)
echo "Setting up Git Username and Email"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

SENTINEL="PLEASE_SET"
unset_vars=()

if [ "$GIT_USERNAME" = "$SENTINEL" ] || [ -z "$GIT_USERNAME" ]; then
    unset_vars+=("GIT_USERNAME")
fi

if [ "$GIT_EMAIL" = "$SENTINEL" ] || [ -z "$GIT_EMAIL" ]; then
    unset_vars+=("GIT_EMAIL")
fi

if [ ${#unset_vars[@]} -gt 0 ]; then
    echo -e "${RED}WARNING: Skipping git config -- the following are unset: ${unset_vars[*]}${NC}"
else
    git config --global user.name "$GIT_USERNAME"
    git config --global user.email "$GIT_EMAIL"
    echo -e "${GREEN}SUCCESS: git configured as $GIT_USERNAME <$GIT_EMAIL>${NC}"
fi
echo "Done setting up Git Username and Email"

echo "Done, time to AutoInterp!"